export const animalList = {
    animals: [
        {
        imageUrl: "../images/animals/cat1.jpg",
        name: "Biscuits",
        sex: "Female",
        breed: "Domestic Short Hair (mix)",
        color: "Black & White",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "2 years",
        description: "Hi! My name is Biscuits. I was named that by the nice lady who rescued me because I love kneading soft, cuddly blankets. I am a playful young lady and love playing with laser mice but I can also be very sweet and loving. Why don’t fill out an application and come on down to let me interview you? You will have a great time! I'll be waiting for you in the Pink Room."
      },
      {
        imageUrl: "../images/animals/cat2.jpg",
        name: "Bluebell",
        sex: "Female",
        breed: "Domestic Short Hair (mix)",
        color: "Orange tabby and white",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "9 years",
        description: "Hi! My name is Bluebell. I contracted FeLV and am now sharing a room with Mama Lyana who, is also FeLV positive. As you can see, I am a stunning girl with the most beautiful eyes ever. I am as sweet as can be and once I warm up to you, I will cuddle in your lap for hours! My roommate Mama Lyana is very shy and I help her be brave and show her that humans are nice and bring yummy food! We need to find a home together so that we can help each other be comfortable in our furrever home. Although there is no cure for FeLV, cats who are positive for the virus can remain healthy for years after their diagnosis until the virus becomes active. In fact, some cats can live to 10-15 years old if they are diagnosed as an adult (as Mama Lyana was)"
      },
      {
        imageUrl: "../images/animals/cat3.jpg",
        name: "Bree Van De Kamp",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Brown Tabby & White",
        coat: "Short	",
        altered: "Yes",
        age: "1 year",
        description: "My name is Bree Van de Kamp. Although my Desperate Housewives namesake is constantly involved in drama, I prefer to play with my sisters Edie, Gabrielle and Lynette and relax in comfy beds. I am the most outgoing of my family and love to play with toy mousies (especially drown them in my water bowl). I would really like to go home with at least one of my sisters so that we can explore our new home together and I can help her be comfortable with our purrrson."
      },
      {
        imageUrl: "../images/animals/cat4.jpg",
        name: "Cardi",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Tortoiseshell / Black",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "5 years",
        description: "Hi ! My name is Cardi, I am a sweet girl who loves head scratches and tummy rubs! I was adopted after I raised 5 wonderful kittens but was returned. After I came back, I was found to be FIV positive.. The wonderful folks here at Cat Angels wanted you to understand a bit more about FIV so they put in the below from Vetinfo.com Feline immunoddeficiency virus, or FIV, is called feline AIDs because it behaves in the same way inside your cat's body that HIV, the virus that causes AIDS, behaves inside the human body. FIV is not contagious to humans or other species. Though it's contagious from cat to cat, it's difficult to spread; transmission usually requires a deep bite wound, though it can also be spread through blood transfusions and by minor bite wounds if the infected cat's gums are bleeding. It cannot be passed by litter boxes, water or food bowls, or by casual contact; it's very rare for this disease to be spread from mother to kitten. Feline immunodeficiency virus compromises your cat's immune system. This means that he can no longer fight off illnesses and infections, and he'll be vulnerable to a range of secondary infections that may be rare in healthy cats. FIV cats may suffer serious illness, and even death, as a result of illnesses and infections that would be considered quite minor, if they weren't immuno-compromised. The good news is that cats with FIV may never display symptoms; they may live normal, happy, healthy life spans. Caring for a cat with FIV is much the same as caring for any other cat; you must simply be extra vigilant for signs of illness. FIV cats must be kept indoors at all times, and away from contact with non-infected cats, though they may be allowed contact with other FIV positive cats. FIV cats should be kept as free as possible from stress. They should enjoy a high quality, high protein diet. Secondary infections should be watched for and any health problems, no matter how minor they might seem, should be treated immediately as they arise."
      },
      {
        imageUrl: "../images/animals/cat5.jpg",
        name: "Chiquita",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Brown Mackeral Tabby",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "10 years",
        description: "Hi! My name is Chiquita and I was born on 3/26/2010. My picture may look bored, but I'm not really. I was just going for that fashion model pout during the photo shoot. Did I do it right? (Pssst.... I have the prettiest eyes you will ever see - just sayin'!) I have recently begun exploring the benefits of being a lap cat! Will you be my new purrson?"
      },
      {
        imageUrl: "../images/animals/cat6.jpg",
        name: "Coco Chanel",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Black Tuxedo",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "2 years",
        description: "Hi, I am Coco Chanel! Like my namesake I am sophisticated and stylish. I am more reserved than my siblings but will warm up to you if you give me some time. I am a playful young cat that loves to run around."
      },
      {
        imageUrl: "../images/animals/cat7.jpg",
        name: "Curtiss",
        sex: "Male",
        breed: "Domestic Short Hair",
        color: "Black",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "5 years",
        description: "Curtiss is a handsome boy who will undoubtedly steal your heart when you meet him. He is a bit shy but can be talkative when he gets to know you. He continues to grow thanks to lots and lots of love. He has become best buds with another shy kitty named Phemie and they provider emotional support to each other and they will need to find a furever home together. Come meet this wonderful kitty and enjoy watching him play with the other kitties!"
      },
      {
        imageUrl: "../images/animals/cat8.jpg",
        name: "Dawn",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Brown Tabby",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "11 years",
        description: "Hi ! My name is Dawn. I came to Cat Angels with my week old kitten. I was scared and wasn't sure what to think of the people here, but they gave me lots of yummy food and made sure that my little girl was warm and had toys to play with. I love my little girl Toni and am protective of her. She is much braver and more trusting than me since the volunteers made sure to play with her. I am still unsure about humans, but am growing more trusting every day. Because I love my little girl, i want to find a home where I can keep an eye on her always. Come visit both of us in the Purple room!"
      },
      {
        imageUrl: "../images/animals/cat9.jpg",
        name: "Edie Britt",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Brown Tabby and White",
        coat: "Short",
        altered: "Yes",
        age: "1 year",
        description: "My name is Edie Britt. Although my Desperate Housewives namesake likes to play the field, I prefer to play with toy mousies! I also like to play with my sisters Bree, Gabrielle and Lynette. I am shy and prefer to observe my surrounding from afar before joining in the fun.. I would really like to go home with at least one of my sisters so that we can explore our new home together and help each other be comfortable with our new purrrson."
      },
      {
        imageUrl: "../images/animals/cat10.jpg",
        name: "Ferguson",
        sex: "Male",
        breed: "Domestic Short Hair",
        color: "Black",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "2 years",
        description: "Hi! My name is Ferguson and I can't wait to meet you! I am a little shy at first, but pull out the laser pointer and am ready to play! I would love to go home with one of my playmates in the yellow room so that I will have a buddy to help me get used to my furrever home."
      },
      {
        imageUrl: "../images/animals/cat11.jpg",
        name: "Gabrielle Solis",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Brown Tabby and White",
        coat: "Short",
        altered: "Yes",
        age: "1 year",
        description: "My name is Gabrielle Solis and although my Desperate Housewives namesake cheated on her partner, I would never cheat on my new human! I love to play with toy mousies and my sisters Bree, Edie and Lynette. I am shy and prefer to observe my surrounding from afar before joining in the fun.. I would really like to go home with at least one of my sisters so that we can explore our new home together and help each other be comfortable with our new purrrson."
      },
      {
        imageUrl: "../images/animals/cat12.jpg",
        name: "Georgette",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Black",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "3 years",
        description: "Hello, my name is Georgette and like my namesake on the Mary Tyler Moore show, I am a sweet girl with a quiet purr. Like my siblings, I can be shy at first, but once I get to know you, I am ready for some lap time! I enjoy a quick game of catch the dot and am a fan of cat nip toys. Come visit me in the purple room today!"
      },
      {
        imageUrl: "../images/animals/cat13.jpg",
        name: "Jane Rizzoli",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Black",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "2 years",
        description: "I'm Jane Rizzoli! I might seem a little shy at first, but I'm actually super sweet! I'll definitely show you some love if you get to know me. Please come visit me soon!"
      },
      {
        imageUrl: "../images/animals/cat14.jpg",
        name: "Lorelei",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Calico",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "1 year",
        description: "Hi! My name is Lorelei. I was found hiding and scared in the outdoor garden area of a local Lowes. A nice person rescued me and brought me here. I like it here. I would love to have a home that is very quiet with lots of love. Will that be with you? Please come down and meet me and let's find out."
      },
      {
        imageUrl: "../images/animals/cat15.jpg",
        name: "Lou",
        sex: "Male",
        breed: "Domestic Short Hair",
        color: "Black",
        coat: "Short",
        altered: "Yes",
        age: "3 years",
        description: "My name is Lou Grant and I am here to make sure that the news from the Purple room is accurate and on time. Although I might appear shy at first, I am really just deciding if you are news worthy, If you are, then I will reward you with a big purr and even a cuddle. I am structurally a big boy, but I could stand to lose a pound or two (darn newsroom donuts!). Stop by and see me for an interview in the purple room today!"
      },
      {
        imageUrl: "../images/animals/cat16.jpg",
        name: "Lynette Scavo",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Brown Tabby and White",
        coat: "Short",
        altered: "Yes",
        age: "1 year",
        description: "Hi! My name is Lynette Scavo. Although my Desperate Housewives namesakeis constantly involved in scandals and cover-ups, I am more low key and stay out of the spotlight. I like to play with my sisters Bree, Gabrielle and Edie. I am shy and prefer to observe my surrounding from afar before joining in the fun.. I would really like to go home with at least one of my sisters so that we can explore our new home together and help each other be comfortable with our new purrrson."
      },
      {
        imageUrl: "../images/animals/cat17.jpg",
        name: "Mama Lyana",
        sex: "Female",
        breed: "Domestic Long Hair",
        color: "Dilute Tortoiseshell",
        coat: "Long",
        altered: "Yes",
        age: "Unknown",
        description: "Mama Lyana was rescued from a home with too many cats. She is a sweet girl, but is timid and shy around strangers, If you sit quietly, she will come out and accept pets. She is rooming with Blue Bell, who helps her feel safe and shows her that humans are nice and give treats. Because of this, Mama Lyana and Blue Bell must find their furrever home together.. Unfortunately, when she arrived at Cat Angels, she tested positive for FeLV (Feline Leukemia Virus). Although there is no cure for FeLV, cats who are positive for the virus can remain healthy for years after their diagnosis until the virus becomes active. In fact, some cats can live to 10-15 years old if they are diagnosed as an adult (as Mama Lyana was)."
      },
      {
        imageUrl: "../images/animals/cat18.jpg",
        name: "Mary Tyler Moore",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Black sml white locket bikini",
        coat: "Short",
        altered: "Yes",
        age: "3 years",
        description: "Hi! I am Mary Tyler Moore and although I can't turn the world on with my smile, I can certainly turn your world on with my purr and sweet meow! I am a little shy at first, but once I warm up, I enjoy a good cuddle. Come visit me in the purple room today!"
      },
      {
        imageUrl: "../images/animals/cat19.jpg",
        name: "Mater",
        sex: "Male",
        breed: "Domestic Short Hair",
        color: "Orange and White",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "2 years",
        description: "Hi! My name is Mater. In the movie Cars, my sidekick was Lighting Mc Queen. In the yellow room, my sidekick and best buddy is the Fonz. We love to cuddle together and when I was returned to shelter from my first home because I was very scared, the first place I went was into the cubby with my buddy! I will have to go home with him since we are both shy and we can help each other not be so scared of new things. Come visit us today in the yellow room!"
      },
      {
        imageUrl: "../images/animals/cat20.jpg",
        name: "Octavius",
        sex: "Male",
        breed: "Domestic Short Hair",
        color: "Black & White Tux",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "5 years",
        description: "I am Octavius! And I love to snuggle with other cats! I am quite gentle and love all the other kitties I’ve met here at Cat Angels. If you take a peek in the Green Room, you’ll see me happily participating in mutual grooming sessions and I particularly like the way my Siamese buddies have taught me the joy of the sleeping pile! I've never been alone before so I need to go home with a buddy from my room. I’ll let you in on a secret, though, as much I love other kitties, I really love people and I am constantly on the lookout for my family to come in so I can claim them! I take my time before coming over to check you out; I have to see how you do with the other kitties first. Then – watch out! Lap – here I come!"
      },
      {
        imageUrl: "../images/animals/cat21.jpg",
        name: "Olivia Manning",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Black & White Tuxedo",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "8 years",
        description: "Hi! My name is Olivia Manning. I'm part of the Manning family of football cats. My sons Eli and Peyton are talented football cats. My husband Archie was a talented football cat too. I'm looking for my forever home with someone who appreciates football and cats. I love being around people but am frightened around other animals. I need a quiet home where I will always be the only pet in the house. I'd love to find my human who will play with toy mousies and ping pong balls with me. Will that be you?"
      },
      {
        imageUrl: "../images/animals/cat22.jpg",
        name: "Potsie",
        sex: "Male",
        breed: "Domestic Short Hair",
        color: "Orange and White",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "3 years",
        description: "Hi! I'm Potsie from the Happy Days crew! My brothers are The Fonz and Richie Cunningham. I love to play with the other kitties! I am very shy towards humans, but given the chance I would warm up and become a great companion. I would love to interview you; if you don't pass Fonzie's sniff test for leather, look at me! Our Mom was Marion Cunningham and she is a love bug lap kitty that's already in her forever home. So we've got GREAT pedigree!"
      },
      {
        imageUrl: "../images/animals/cat23.jpg",
        name: "Sally Brown",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Black Tuxedo",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "4 years",
        description: "Hello! Sally Brown here! Yes, I was named after Charlie Brown's little sister from the Peanuts. Like her, I am a sweet girl, but I more reserved than my curly haired namesake. But once I get warmed up, I can talk up a storm! I enjoy playing a game of catch the dot and am not going to refuse a good catnip toy. Come visit me and see if you want to take home your own version of Charlie Brown's annoying little sister."
      },
      {
        imageUrl: "../images/animals/cat24.jpg",
        name: "Susan",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Brown Ticked Tabby",
        coat: "Short",
        altered: "Yes",
        age: "1 year",
        description: "Hi! My name is Susan Mayer. Like my namesake on DEparate Housewives, I am a single mother-although I have 4 daughters instead of 1. I have given up searching for love in my own specieis nd have decided to look for the love of my life in a purrson. I am a little shy in new situations, but it does not take me long to blossom and show you my sweet side. I would like to find a home with one of my girls as they still need some help in learning to trust humans and understand that they are good.. Come visit me and my girls in the pink room today!"
      },
      {
        imageUrl: "../images/animals/cat25.jpg",
        name: "The Fonz",
        sex: "Male",
        breed: "Domestic Short Hair",
        color: "Gray tabby and white",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "3 years",
        description: "Hi! I’m the Fonz!!! Well, at least I’m the Fonz before he grew into his large and self-confident personality. Right now, I’m still learning the ropes of this thing called life. I am shy around humans, but my friend Mater helps me and I help him in adjusting to new cats and getting braver around the humans. I have been put in charge of finding the furever family for myself and Mater since I'll know them the minute I smell leather! Ha ha!!!"
      },
      {
        imageUrl: "../images/animals/cat26.jpg",
        name: "Toni Orlando",
        sex: "Female",
        breed: "Domestic Short Hair",
        color: "Brown Tabby",
        coat: "Unknown or N/A",
        altered: "Yes",
        age: "2 years",
        description: "Hi ! My name is Toni Orlando. I arrived as Cat Angels as a tiny kitten with my mom Dawn. She took very good care of me and made sure that I had good food and was warm. Even though she was scared of the humans, I found out that the volunteers liked to play with me and give me yummy treats. Even though I am a big girl now, my mom still likes to keep a close eye on me and I help her trust the humans. We will need to find a home together so that I can help her become more comfortable around humans. Come visit us in the Purple room!"
      }
    ]
}